% Sort two poses according to their reprojection error
%
% Usage:
%   [R1,R2,t1,t2,reprojErr1,reprojErr2] = sortSolutions(R1,R2,t1,t2,reprojErr1,reprojErr2)
%
% Inputs:
%   R1, R2 = 3*3 rotation matrix
%   t1, t2 = 1*3 translation vectors
%   K = 3*3 intrinsic matrix
%   P = 3*n matrix, which are n 3*1 vectors indicate the image plane coordinates of correspondences
%   Q = 2*n matrix, which are n 2*1 vectors indicate the normalized image pixel coordinates of correspondences
%
% Outputs:
%   R1, t1 = rotation matrix and translation vectors with smaller reprojection error
%   R2, t2 = rotation matrix and translation vectors with bigger reprojection error
%   reprojErr1, reprojErr2 = corresponding reprojection errors

% This code is implemented by Tobby Collins in the work "Infinitesimal Plane-based Pose Estimation", IJCV 2014.
function [R1,R2,t1,t2,reprojErr1,reprojErr2] = sortSolutions(R1,R2,t1,t2,K,P,Q)
  [reprojErr1,reprojErr2] = computeReprojErrs(R1,R2,t1,t2,K,P,Q);
  if reprojErr2<reprojErr1
      [R1,R2,t1,t2,reprojErr1,reprojErr2] = swapSolutions(R1,R2,t1,t2,reprojErr1,reprojErr2);
  end
end

function [reprojErr1,reprojErr2] = computeReprojErrs(R1,R2,t1,t2,K,P,Q)
  %computeReprojErrs: Computes the reprojection errors for the two solutions
  %generated by IPPE.
  
  %transform model points to camera coordinates and project them onto the
  %image:
  PCam1 = R1(:,1:2)*P(1:2,:);
  PCam1(1,:) = PCam1(1,:) + t1(1);
  PCam1(2,:) = PCam1(2,:) + t1(2);
  PCam1(3,:) = PCam1(3,:) + t1(3);
  
  PCam2 = R2(:,1:2)*P(1:2,:);
  PCam2(1,:) = PCam2(1,:) + t2(1);
  PCam2(2,:) = PCam2(2,:) + t2(2);
  PCam2(3,:) = PCam2(3,:) + t2(3);
  
  Qest_1 = K*PCam1;
  Qest_1 = Qest_1./[Qest_1(3,:);Qest_1(3,:);Qest_1(3,:)];
  
  Qest_2 = K*PCam2;
  Qest_2 = Qest_2./[Qest_2(3,:);Qest_2(3,:);Qest_2(3,:)];
  
  %compute reprojection errors:
  reprojErr1 = norm(Qest_1(1:2,:)-Q);
  reprojErr2 = norm(Qest_2(1:2,:)-Q);
end

function [R1,R2,t1,t2,reprojErr1,reprojErr2] = swapSolutions(R1_,R2_,t1_,t2_,reprojErr1_,reprojErr2_)
  %swaps the solutions:
  R1 = R2_;
  t1 = t2_;
  reprojErr1 = reprojErr2_;
  
  R2 = R1_;
  t2 = t1_;
  reprojErr2 = reprojErr1_;
end